//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metting_Minutes.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metting_Details
    {
        public int id { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string AttendsFromClientSide { get; set; }
        public string AttendsFromHostSide { get; set; }
        public string MeettingAgenda { get; set; }
        public string MeetingDisCussion { get; set; }
        public string MettingDecision { get; set; }
        public string MeetingPlace { get; set; }
    }
}
