//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metting_Minutes.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Metting_MinutesEntities1 : DbContext
    {
        public Metting_MinutesEntities1()
            : base("name=Metting_MinutesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Corporate_table> Corporate_table { get; set; }
        public DbSet<FinalProduct> FinalProducts { get; set; }
        public DbSet<Individual_table> Individual_table { get; set; }
        public DbSet<Metting_Details> Metting_Details { get; set; }
        public DbSet<Product_Unit> Product_Unit { get; set; }
    }
}
