//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metting_Minutes.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Unit
    {
        public int id { get; set; }
        public string Product_Service { get; set; }
        public string Unit { get; set; }
    }
}
